### ISSUE TITLE
App fails to parse multiversebridge.com

### ISSUE THREAD

**Issue by Drakonas** [smcasey907/dragonshield-cardsphere#1]
Tried using the tool, but it seems that the code is failing due to a schema issue. The website does not respond to http://multiversebridge.com. http://www.multiversebridge.com is required. The domain's DNS settings make "www" mandatory apparently.

```PS X:\Google Drive\Games\MTG\Dragon Shield Exports\dragonshield-cardsphere> .\win_ds-cs.ps1
Welcome to the Dragon Shield Collection Export
to Cardsphere csv importer. Be patient
while the kobolds eat...er, massage your data...

Getting data from binder:
Large Black Binder
Traceback (most recent call last):
  File "X:\Google Drive\Games\MTG\Dragon Shield Exports\dragonshield-cardsphere\app\cardsphere.py", line 26, in <module>
    totalCounted += pd.processCards(cardList)
  File "X:\Google Drive\Games\MTG\Dragon Shield Exports\dragonshield-cardsphere\app\processData.py", line 71, in processCards
    totalQuantity = addCardToDataCollection(c, totalQuantity)
  File "X:\Google Drive\Games\MTG\Dragon Shield Exports\dragonshield-cardsphere\app\processData.py", line 85, in addCardToDataCollection
    rVal = service.getCardData(query)
  File "X:\Google Drive\Games\MTG\Dragon Shield Exports\dragonshield-cardsphere\app\multiverseBridgeService.py", line 22, in getCardData
    response = http.get(api_url, params=query)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "C:\Python310\lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "C:\Python310\lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "C:\Python310\lib\site-packages\requests\models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'multiversebridge.com/api/v1/cards/search?': No scheme supplied. Perhaps you meant http://multiversebridge.com/api/v1/cards/search??
```

**Comment by Drakonas** [comment]
I have submitted a pull request that fixes the issue. http://www.multiversebridge.com needs to be used instead of just multiversebridge.com.
